-- MySQL Script generated by MySQL Workbench
-- Wed Aug 20 12:33:15 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- =====================================================
-- Schema: NAGPRAworkflowdb
-- Description: Database for managing NAGPRA repatriation workflows
-- =====================================================

CREATE SCHEMA IF NOT EXISTS `NAGPRAworkflowdb` 
    DEFAULT CHARACTER SET utf8mb4 
    COLLATE utf8mb4_unicode_ci;

USE `NAGPRAworkflowdb`;

-- =====================================================
-- Core Entity Tables
-- =====================================================

-- -----------------------------------------------------
-- Table: Community
-- Description: Tribes and Native Hawaiian Organizations
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NAGPRAworkflowdb`.`Community` (
    `community_id` INT NOT NULL AUTO_INCREMENT,
    `community_type` ENUM('tribe', 'NHO') NOT NULL,
    `community_name` VARCHAR(255) NOT NULL,
    `community_federal_status` ENUM('federally_recognized', 'state_recognized', 'unrecognized', 'n/a - NHO') NOT NULL,
    `community_thpo_office` VARCHAR(255) NULL,
    `community_thpo_recognized` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Boolean flag for THPO recognition',
    `community_thpo_recognized_on` DATE NULL,
    `community_website` VARCHAR(255) NULL,
    `community_notes` TEXT NULL,
    PRIMARY KEY (`community_id`),
    UNIQUE INDEX `community_name_UNIQUE` (`community_name` ASC) VISIBLE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table: Institution
-- Description: Museums, universities, and other institutions
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NAGPRAworkflowdb`.`Institution` (
    `institution_id` INT NOT NULL AUTO_INCREMENT,
    `institution_name` VARCHAR(255) NOT NULL,
    `institution_type` ENUM('museum', 'university', 'federal_agency', 'state_agency', 'private_collection', 'other') NOT NULL,
    `institution_address_street` VARCHAR(255) NULL,
    `institution_city` VARCHAR(64) NOT NULL,
    `institution_state` VARCHAR(64) NOT NULL,
    `institution_postal_code` VARCHAR(10) NOT NULL,
    `institution_country` VARCHAR(32) NOT NULL,
    `institution_nps_org_id` VARCHAR(64) NULL,
    `institution_notes` TEXT NULL,
    PRIMARY KEY (`institution_id`),
    UNIQUE INDEX `institution_name_UNIQUE` (`institution_name` ASC) VISIBLE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table: Contact
-- Description: People involved in the repatriation process
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NAGPRAworkflowdb`.`Contact` (
    `contact_id` INT NOT NULL AUTO_INCREMENT,
    `contact_name` VARCHAR(255) NOT NULL,
    `contact_role` ENUM('THPO', 'EldersCouncil', 'Curator', 'CollectionsMgr', 'Legal', 'Researcher', 'Other') NOT NULL,
    `contact_email` VARCHAR(255) NULL,
    `contact_phone` VARCHAR(50) NULL,
    `contact_community_id` INT NULL,
    `contact_institution_id` INT NULL,
    PRIMARY KEY (`contact_id`),
    INDEX `fk_contact_community_idx` (`contact_community_id` ASC) VISIBLE,
    INDEX `fk_contact_institution_id_idx` (`contact_institution_id` ASC) VISIBLE,
    CONSTRAINT `fk_contact_community_id`
        FOREIGN KEY (`contact_community_id`)
        REFERENCES `NAGPRAworkflowdb`.`Community` (`community_id`)
        ON DELETE SET NULL
        ON UPDATE CASCADE,
    CONSTRAINT `fk_contact_institution_id`
        FOREIGN KEY (`contact_institution_id`)
        REFERENCES `NAGPRAworkflowdb`.`Institution` (`institution_id`)
        ON DELETE SET NULL
        ON UPDATE CASCADE
) ENGINE = InnoDB;

-- =====================================================
-- Cultural Items and Remains
-- =====================================================

-- -----------------------------------------------------
-- Table: CulturalItem
-- Description: Base table for all cultural items and remains
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NAGPRAworkflowdb`.`CulturalItem` (
    `item_id` INT NOT NULL AUTO_INCREMENT,
    `item_category` ENUM('human_remains', 'associated_funerary_object', 'unassociated_funerary_object', 'sacred_object', 'object_of_cultural_patrimony') NOT NULL,
    `item_title` VARCHAR(255) NULL,
    `item_description` TEXT NULL,
    `item_date_range` VARCHAR(255) NULL,
    `item_haz_treated` TINYINT(1) NOT NULL DEFAULT 0,
    `item_haz_notes` TEXT NULL,
    `item_created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`item_id`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table: RemainsProfile
-- Description: Detailed information about human remains
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NAGPRAworkflowdb`.`RemainsProfile` (
    `item_id` INT NOT NULL,
    `remains_individual_min` INT NULL,
    `remains_individual_max` INT NULL,
    `remains_sex_estimation` ENUM('indeterminate', 'probable_male', 'male', 'probable_female', 'female') NULL,
    `remains_age_estimation` VARCHAR(64) NULL,
    `remains_osteology_notes` TEXT NULL,
    PRIMARY KEY (`item_id`),
    CONSTRAINT `fk_remainsprofile_item_id`
        FOREIGN KEY (`item_id`)
        REFERENCES `NAGPRAworkflowdb`.`CulturalItem` (`item_id`)
        ON DELETE CASCADE
        ON UPDATE CASCADE
) ENGINE = InnoDB;

-- =====================================================
-- Geographic and Site Information
-- =====================================================

-- -----------------------------------------------------
-- Table: DiscoverySite
-- Description: Archaeological and discovery sites
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NAGPRAworkflowdb`.`DiscoverySite` (
    `site_id` INT NOT NULL AUTO_INCREMENT,
    `site_name` VARCHAR(255) NULL,
    `site_county` VARCHAR(64) NULL,
    `site_state` VARCHAR(64) NOT NULL,
    `site_country` VARCHAR(32) NOT NULL,
    `site_latitude` DECIMAL(9,6) NULL,
    `site_longitude` DECIMAL(9,6) NULL,
    `site_restricted` TINYINT(1) NULL DEFAULT 1,
    `site_sensitive_notes` TEXT NULL,
    PRIMARY KEY (`site_id`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table: ItemSite
-- Description: Relationship between items and discovery sites
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NAGPRAworkflowdb`.`ItemSite` (
    `item_id` INT NOT NULL,
    `site_id` INT NOT NULL,
    `relation_role` ENUM('findspot', 'probable_origin', 'reported_origin', 'other') NOT NULL DEFAULT 'findspot',
    PRIMARY KEY (`item_id`, `site_id`),
    INDEX `fk_site_id_idx` (`site_id` ASC) VISIBLE,
    CONSTRAINT `fk_itemsite_item_id`
        FOREIGN KEY (`item_id`)
        REFERENCES `NAGPRAworkflowdb`.`CulturalItem` (`item_id`)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT `fk_itemsite_site_id`
        FOREIGN KEY (`site_id`)
        REFERENCES `NAGPRAworkflowdb`.`DiscoverySite` (`site_id`)
        ON DELETE CASCADE
        ON UPDATE CASCADE
) ENGINE = InnoDB;

-- =====================================================
-- Institutional Holdings and Management
-- =====================================================

-- -----------------------------------------------------
-- Table: Holding
-- Description: How institutions possess and manage cultural items
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NAGPRAworkflowdb`.`Holding` (
    `holding_id` INT NOT NULL AUTO_INCREMENT,
    `item_id` INT NOT NULL,
    `institution_id` INT NOT NULL,
    `holding_catalog_number` VARCHAR(120) NULL,
    `holding_accession_number` VARCHAR(120) NULL,
    `holding_collection_name` VARCHAR(255) NULL,
    `holding_acquisition` ENUM('donation', 'purchase', 'field_collection', 'transfer', 'seizure', 'unknown') NULL DEFAULT 'unknown',
    `holding_source_party` VARCHAR(255) NULL,
    `holding_acquired_on` DATE NULL,
    `holding_type` ENUM('possession', 'control', 'custody') NOT NULL DEFAULT 'possession',
    `holding_owns_title` TINYINT(1) NOT NULL DEFAULT 0,
    `holding_rop` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Right of Possession',
    `holding_rop_basis` TEXT NULL,
    `holding_storage_location` VARCHAR(255) NULL,
    `holding_on_exhibit` TINYINT(1) NOT NULL DEFAULT 0,
    `holding_condition_notes` TEXT NULL,
    `holding_start_date` DATE NOT NULL,
    `holding_end_date` DATE NULL,
    `holding_current` TINYINT(1) NOT NULL DEFAULT 1,
    `holding_summary_submit` DATE NULL,
    `holding_inv_complete` DATE NULL,
    `holding_accession_doc` VARCHAR(255) NULL,
    `holding_loan_agreement` VARCHAR(255) NULL,
    `holding_chain_of_custody` VARCHAR(255) NULL,
    PRIMARY KEY (`holding_id`),
    INDEX `fk_item_id_idx` (`item_id` ASC) VISIBLE,
    INDEX `fk_institution_id_idx` (`institution_id` ASC) VISIBLE,
    CONSTRAINT `fk_holding_item_id`
        FOREIGN KEY (`item_id`)
        REFERENCES `NAGPRAworkflowdb`.`CulturalItem` (`item_id`)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,
    CONSTRAINT `fk_holding_institution_id`
        FOREIGN KEY (`institution_id`)
        REFERENCES `NAGPRAworkflowdb`.`Institution` (`institution_id`)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
) ENGINE = InnoDB;

-- =====================================================
-- Affiliation and Consultation
-- =====================================================

-- -----------------------------------------------------
-- Table: Affiliation
-- Description: Cultural and lineal affiliations between items and communities
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NAGPRAworkflowdb`.`Affiliation` (
    `affiliation_id` INT NOT NULL AUTO_INCREMENT,
    `item_id` INT NOT NULL,
    `community_id` INT NOT NULL,
    `affiliation_type` ENUM('lineal', 'cultural') NOT NULL,
    `affiliation_basis` TEXT NULL,
    `affiliation_determined` DATE NULL,
    PRIMARY KEY (`affiliation_id`),
    INDEX `fk_item_id_idx` (`item_id` ASC) VISIBLE,
    INDEX `fk_community_id_idx` (`community_id` ASC) VISIBLE,
    UNIQUE INDEX `uq_affiliation_item_comm_type` (`item_id` ASC, `community_id` ASC, `affiliation_type` ASC) VISIBLE,
    CONSTRAINT `fk_affiliation_item_id`
        FOREIGN KEY (`item_id`)
        REFERENCES `NAGPRAworkflowdb`.`CulturalItem` (`item_id`)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT `fk_affiliation_community_id`
        FOREIGN KEY (`community_id`)
        REFERENCES `NAGPRAworkflowdb`.`Community` (`community_id`)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table: Consultation
-- Description: Consultation process between institutions and communities
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NAGPRAworkflowdb`.`Consultation` (
    `consult_id` INT NOT NULL AUTO_INCREMENT,
    `item_id` INT NOT NULL,
    `community_id` INT NOT NULL,
    `institution_id` INT NOT NULL,
    `consult_started_on` DATE NULL,
    `consult_last_meeting` DATE NULL,
    `consult_status` ENUM('not_started', 'in_progress', 'paused', 'complete') NOT NULL DEFAULT 'in_progress',
    `consult_notes` TEXT NULL,
    PRIMARY KEY (`consult_id`),
    INDEX `fk_item_id_idx` (`item_id` ASC) VISIBLE,
    INDEX `fk_community_id_idx` (`community_id` ASC) VISIBLE,
    INDEX `fk_institution_id_idx` (`institution_id` ASC) VISIBLE,
    CONSTRAINT `fk_consultation_item_id`
        FOREIGN KEY (`item_id`)
        REFERENCES `NAGPRAworkflowdb`.`CulturalItem` (`item_id`)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT `fk_consultation_community_id`
        FOREIGN KEY (`community_id`)
        REFERENCES `NAGPRAworkflowdb`.`Community` (`community_id`)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,
    CONSTRAINT `fk_consultation_institution_id`
        FOREIGN KEY (`institution_id`)
        REFERENCES `NAGPRAworkflowdb`.`Institution` (`institution_id`)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
) ENGINE = InnoDB;

-- =====================================================
-- Repatriation Process
-- =====================================================

-- -----------------------------------------------------
-- Table: RepatriationRequest
-- Description: Formal requests for repatriation
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NAGPRAworkflowdb`.`RepatriationRequest` (
    `request_id` INT NOT NULL AUTO_INCREMENT,
    `item_id` INT NOT NULL,
    `requesting_community_id` INT NOT NULL,
    `request_received_on` DATE NOT NULL,
    `request_acknowledged_on` DATE NULL,
    `request_decision` ENUM('approved', 'pending', 'denied', 'withdrawn') NOT NULL DEFAULT 'pending',
    `request_decision_on` DATE NULL,
    `request_basis` TEXT NULL,
    PRIMARY KEY (`request_id`),
    INDEX `fk_item_id_idx` (`item_id` ASC) VISIBLE,
    INDEX `fk_requesting_community_id_idx` (`requesting_community_id` ASC) VISIBLE,
    CONSTRAINT `fk_requested_item_id`
        FOREIGN KEY (`item_id`)
        REFERENCES `NAGPRAworkflowdb`.`CulturalItem` (`item_id`)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT `fk_requesting_community_id`
        FOREIGN KEY (`requesting_community_id`)
        REFERENCES `NAGPRAworkflowdb`.`Community` (`community_id`)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table: Transfer
-- Description: Physical transfer of items from institutions to communities
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NAGPRAworkflowdb`.`Transfer` (
    `transfer_id` INT NOT NULL AUTO_INCREMENT,
    `item_id` INT NOT NULL,
    `from_institution_id` INT NOT NULL,
    `to_community_id` INT NOT NULL,
    `transfer_scheduled_on` DATE NULL,
    `transfer_completed_on` DATE NULL,
    `transfer_transport` VARCHAR(120) NULL,
    `transfer_location` VARCHAR(120) NULL,
    `transfer_tracking_number` VARCHAR(64) NULL,
    `transfer_handover_contact` INT NULL,
    `transfer_receive_contact` INT NULL,
    `transfer_chain_of_custody_document` VARCHAR(255) NULL,
    `transfer_notes` TEXT NULL,
    PRIMARY KEY (`transfer_id`),
    INDEX `fk_item_id_idx` (`item_id` ASC) VISIBLE,
    INDEX `fk_from_institution_id_idx` (`from_institution_id` ASC) VISIBLE,
    INDEX `fk_to_community_id_idx` (`to_community_id` ASC) VISIBLE,
    INDEX `fk_transfer_handover_contact_idx` (`transfer_handover_contact` ASC) VISIBLE,
    INDEX `fk_transfer_receive_contact_idx` (`transfer_receive_contact` ASC) VISIBLE,
    CONSTRAINT `fk_transfer_item_id`
        FOREIGN KEY (`item_id`)
        REFERENCES `NAGPRAworkflowdb`.`CulturalItem` (`item_id`)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT `fk_transfer_from_institution_id`
        FOREIGN KEY (`from_institution_id`)
        REFERENCES `NAGPRAworkflowdb`.`Institution` (`institution_id`)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,
    CONSTRAINT `fk_transfer_to_community_id`
        FOREIGN KEY (`to_community_id`)
        REFERENCES `NAGPRAworkflowdb`.`Community` (`community_id`)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,
    CONSTRAINT `fk_transfer_handover_contact_id`
        FOREIGN KEY (`transfer_handover_contact`)
        REFERENCES `NAGPRAworkflowdb`.`Contact` (`contact_id`)
        ON DELETE SET NULL
        ON UPDATE CASCADE,
    CONSTRAINT `fk_transfer_receive_contact_id`
        FOREIGN KEY (`transfer_receive_contact`)
        REFERENCES `NAGPRAworkflowdb`.`Contact` (`contact_id`)
        ON DELETE SET NULL
        ON UPDATE CASCADE
) ENGINE = InnoDB;

-- =====================================================
-- Restore Original Settings
-- =====================================================

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
