-- Full demonstration seed adapted from the original coursework seed.
-- Migration 3/5: loads synthetic demonstration data for the public portfolio deployment.

begin;

truncate table transfer, repatriation_request, consultation, affiliation, holding, item_site, remains_profile, cultural_item, contact, institution, discovery_site, community restart identity cascade;

-- 2) Communities
INSERT INTO
    community (
        community_id,
        community_type,
        community_name,
        community_federal_status,
        community_thpo_office,
        community_thpo_recognized,
        community_thpo_recognized_on,
        community_website,
        community_notes
    )
VALUES
    (
        1,
        'tribe',
        'Sault Ste. Marie Tribe of Chippewa Indians',
        'federally_recognized',
        'Historic Preservation Department',
        1,
        '2008-06-15',
        'https://ssmtribe.example',
        'Primary NAGPRA contact is THPO.'
    ),
    (
        2,
        'tribe',
        'Bay Mills Indian Community',
        'federally_recognized',
        NULL,
        0,
        NULL,
        'https://baymills.example',
        NULL
    ),
    (
        3,
        'tribe',
        'Keweenaw Bay Indian Community',
        'federally_recognized',
        'THPO Office',
        1,
        '2012-03-05',
        'https://kbic.example',
        NULL
    ),
    (
        4,
        'tribe',
        'Match-E-Be-Nash-She-Wish Band of Pottawatomi Indians',
        'federally_recognized',
        NULL,
        0,
        NULL,
        'https://gunlake.example',
        NULL
    ),
    (
        5,
        'tribe',
        'Little Traverse Bay Bands of Odawa Indians',
        'federally_recognized',
        'Cultural Preservation',
        1,
        '2010-10-10',
        'https://ltbb.example',
        ''
    ),
    (
        6,
        'NHO',
        'Office of Hawaiian Affairs',
        'n/a - NHO',
        'Heritage Program',
        1,
        '2001-01-01',
        'https://oha.example',
        ''
    ),
    (
        7,
        'tribe',
        'Pokagon Band of Potawatomi Indians',
        'federally_recognized',
        NULL,
        0,
        NULL,
        'https://pokagon.example',
        NULL
    ),
    (
        8,
        'tribe',
        'Lac Vieux Desert Band of Lake Superior Chippewa',
        'federally_recognized',
        'THPO',
        1,
        '2016-09-09',
        'https://lvd.example',
        NULL
    ),
    (
        9,
        'tribe',
        'Grand Traverse Band of Ottawa and Chippewa Indians',
        'federally_recognized',
        'Historic Preservation',
        1,
        '2009-03-20',
        'https://gtb.example',
        NULL
    ),
    (
        10,
        'NHO',
        'Hui Mālama I Nā Kūpuna',
        'n/a - NHO',
        NULL,
        1,
        '1999-05-01',
        'https://huimalama.example',
        'Cares for kūpuna (ancestors).'
    );

-- 3) Institutions
INSERT INTO
    institution (
        institution_id,
        institution_name,
        institution_type,
        institution_address_street,
        institution_city,
        institution_state,
        institution_postal_code,
        institution_country,
        institution_nps_org_id,
        institution_notes
    )
VALUES
    (
        10,
        'Great Lakes University Museum',
        'university',
        '123 Museum Way, Suite 200',
        'Marquette',
        'Michigan',
        '43605',
        'USA',
        'NPS-GLUM-001',
        'Participates in BIA inventory.'
    ),
    (
        11,
        'Northern State Historical Museum',
        'museum',
        '1 Heritage Ave',
        'Houghton',
        'Michigan',
        '49931',
        'USA',
        NULL,
        'Legacy collections.'
    ),
    (
        12,
        'River Valley Archaeology Center',
        'museum',
        '88 River Rd',
        'Sault Ste. Marie',
        'Michigan',
        '49783',
        'USA',
        NULL,
        'Active on consultations.'
    ),
    (
        13,
        'National Park Service - Lakes Region',
        'federal_agency',
        '100 Federal Way',
        'Chicago',
        'Illinois',
        '60604',
        'USA',
        'NPS-LAKE-REG',
        ''
    ),
    (
        14,
        'State Department of History',
        'state_agency',
        '77 Capitol St',
        'Lansing',
        'Michigan',
        '48933',
        'USA',
        NULL,
        ''
    ),
    (
        15,
        'Upper Peninsula University',
        'university',
        '400 Campus Dr',
        'Marquette',
        'Michigan',
        '43606',
        'USA',
        NULL,
        'Small teaching collections.'
    ),
    (
        16,
        'Midwest Private Collections Trust',
        'private_collection',
        '1200 Lake St',
        'Detroit',
        'Michigan',
        '48201',
        'USA',
        NULL,
        'Holding items under trust.'
    ),
    (
        17,
        'Islands Research Museum',
        'museum',
        '50 Pacific Ave',
        'Honolulu',
        'Hawaii',
        '96813',
        'USA',
        NULL,
        'Holds Hawaiian materials.'
    );

-- 4) Contacts
INSERT INTO
    contact (
        contact_id,
        contact_name,
        contact_role,
        contact_email,
        contact_phone,
        contact_community_id,
        contact_institution_id
    )
VALUES
    (
        100,
        'Jordan Freeman',
        'Researcher',
        'jordan@glum.example',
        '(555) 000-1000',
        NULL,
        10
    ),
    (
        101,
        'Aiyana Peters',
        'THPO',
        'aiyana@ssmtribe.example',
        '(555) 000-1001',
        1,
        NULL
    ),
    (
        102,
        'Mason Cole',
        'Curator',
        'mason@riverarch.example',
        '(555) 000-1002',
        NULL,
        12
    ),
    (
        103,
        'Kalea Kealoha',
        'Other',
        'kalea@oha.example',
        '(555) 000-1003',
        6,
        NULL
    ),
    (
        104,
        'Riley Thomas',
        'CollectionsMgr',
        'riley@nshm.example',
        '(555) 000-1004',
        NULL,
        11
    ),
    (
        105,
        'Evelyn White',
        'Legal',
        'evelyn@statehistory.example',
        '(555) 000-1005',
        NULL,
        14
    ),
    (
        106,
        'Noah Martin',
        'THPO',
        'noah@ltbb.example',
        '(555) 000-1006',
        5,
        NULL
    ),
    (
        107,
        'Casey Green',
        'Curator',
        'casey@upuniv.example',
        '(555) 000-1007',
        NULL,
        15
    ),
    (
        108,
        'Piper Wynn',
        'CollectionsMgr',
        'piper@mwpct.example',
        '(555) 000-1008',
        NULL,
        16
    ),
    (
        109,
        'Leilani Pua',
        'Researcher',
        'leilani@islandsrm.example',
        '(555) 000-1009',
        NULL,
        17
    ),
    (
        110,
        'Owen Black',
        'THPO',
        'owen@kbic.example',
        '(555) 000-1010',
        3,
        NULL
    ),
    (
        111,
        'Maya Blue',
        'THPO',
        'maya@gtb.example',
        '(555) 000-1011',
        9,
        NULL
    ),
    (
        112,
        'Harper Fox',
        'Curator',
        'harper@npslakes.example',
        '(555) 000-1012',
        NULL,
        13
    ),
    (
        113,
        'Tala Nakoa',
        'Other',
        'tala@huimalama.example',
        '(555) 000-1013',
        10,
        NULL
    ),
    (
        114,
        'Drew Stone',
        'Researcher',
        'drew@riverarch.example',
        '(555) 000-1014',
        NULL,
        12
    ),
    (
        115,
        'Quinn Lake',
        'Legal',
        'quinn@glum.example',
        '(555) 000-1015',
        NULL,
        10
    ),
    (
        116,
        'Ravi Patel',
        'Curator',
        'ravi@statehistory.example',
        '(555) 000-1016',
        NULL,
        14
    ),
    (
        117,
        'Willow Brooks',
        'CollectionsMgr',
        'willow@nshm.example',
        '(555) 000-1017',
        NULL,
        11
    ),
    (
        118,
        'Kai Kanoa',
        'Researcher',
        'kai@islandsrm.example',
        '(555) 000-1018',
        NULL,
        17
    );

-- 5) Discovery Sites
INSERT INTO
    discovery_site (
        site_id,
        site_name,
        site_county,
        site_state,
        site_country,
        site_latitude,
        site_longitude,
        site_restricted,
        site_sensitive_notes
    )
VALUES
    (
        501,
        'St. Marys River site',
        'Chippewa',
        'Michigan',
        'USA',
        46.495200,
        -84.345100,
        1,
        'Burial area, active cultural use.'
    ),
    (
        502,
        'Grand Marais Dune',
        'Alger',
        'Michigan',
        'USA',
        46.670000,
        -85.980000,
        0,
        NULL
    ),
    (
        503,
        'Copper Harbor Bluff',
        NULL,
        'Michigan',
        'USA',
        47.468000,
        -87.888000,
        0,
        NULL
    ),
    (
        504,
        'Sault Canal Works',
        'Chippewa',
        'Michigan',
        'USA',
        46.502300,
        -84.343900,
        1,
        'Construction salvage context.'
    ),
    (
        505,
        'Keweenaw Ridge',
        'Houghton',
        'Michigan',
        'USA',
        47.120000,
        -88.580000,
        0,
        NULL
    ),
    (
        506,
        'Mackinac Straits Shoal',
        'Mackinac',
        'Michigan',
        'USA',
        45.842000,
        -84.727000,
        1,
        'Underwater cultural landscape.'
    ),
    (
        507,
        'Tahquamenon Overlook',
        'Chippewa',
        'Michigan',
        'USA',
        46.468500,
        -85.176200,
        0,
        NULL
    ),
    (
        508,
        'Sugar Island Point',
        'Chippewa',
        'Michigan',
        'USA',
        46.450100,
        -84.233300,
        1,
        'Sensitive area agreed by THPO.'
    ),
    (
        509,
        'Little Bay de Noc Terrace',
        'Delta',
        'Michigan',
        'USA',
        45.742100,
        -87.020500,
        0,
        NULL
    ),
    (
        510,
        'Old Mission Peninsula',
        'Grand Traverse',
        'Michigan',
        'USA',
        44.941200,
        -85.488800,
        0,
        NULL
    ),
    (
        511,
        'Hawaiian Island Shore',
        'Honolulu',
        'Hawaii',
        'USA',
        21.306900,
        -157.858300,
        1,
        'Kūpuna iwi findspot.'
    ),
    (
        512,
        'Molokaʻi Dune',
        'Maui',
        'Hawaii',
        'USA',
        21.150000,
        -157.000000,
        1,
        'Restricted: burial context.'
    );

-- 6) Cultural Items
INSERT INTO
    cultural_item (
        item_id,
        item_category,
        item_title,
        item_description,
        item_date_range,
        item_haz_treated,
        item_haz_notes,
        item_created_at
    )
VALUES
    -- Human remains (12)
    (
        1001,
        'human_remains',
        'Individual A',
        'Cranial and long-bone fragments',
        'Late 19th century',
        0,
        NULL,
        CURRENT_TIMESTAMP
    ),
    (
        1002,
        'human_remains',
        'Individual B',
        'Mandible and rib fragments',
        NULL,
        0,
        NULL,
        CURRENT_TIMESTAMP
    ),
    (
        1003,
        'human_remains',
        'Individual C',
        'Secondary deposit; mixed context',
        NULL,
        1,
        'Historic arsenic treatment suspected',
        CURRENT_TIMESTAMP
    ),
    (
        1004,
        'human_remains',
        'Individual D',
        'Partial cranium',
        'ca. 1850–1900',
        0,
        NULL,
        CURRENT_TIMESTAMP
    ),
    (
        1005,
        'human_remains',
        'Individual E',
        'Long bone set',
        '19th century',
        0,
        NULL,
        CURRENT_TIMESTAMP
    ),
    (
        1006,
        'human_remains',
        'Individual F',
        'Juvenile remains',
        'Unknown',
        0,
        NULL,
        CURRENT_TIMESTAMP
    ),
    (
        1007,
        'human_remains',
        'Individual G',
        'Adult; teeth present',
        NULL,
        0,
        NULL,
        CURRENT_TIMESTAMP
    ),
    (
        1008,
        'human_remains',
        'Individual H',
        'Commingled small set',
        NULL,
        1,
        'Mercuric chloride label on box',
        CURRENT_TIMESTAMP
    ),
    (
        1009,
        'human_remains',
        'Individual I',
        'Partial post-cranial',
        'Historic',
        0,
        NULL,
        CURRENT_TIMESTAMP
    ),
    (
        1010,
        'human_remains',
        'Individual J',
        'Infant remains',
        'Precontact/Historic',
        0,
        NULL,
        CURRENT_TIMESTAMP
    ),
    (
        1011,
        'human_remains',
        'Individual K',
        'Cranium',
        'Unknown',
        0,
        NULL,
        CURRENT_TIMESTAMP
    ),
    (
        1012,
        'human_remains',
        'Individual L',
        'Multiple ribs and vertebrae',
        NULL,
        0,
        NULL,
        CURRENT_TIMESTAMP
    ),
    -- Associated funerary objects (10)
    (
        2001,
        'associated_funerary_object',
        'Copper beads',
        'String of copper beads',
        'Historic period',
        0,
        NULL,
        CURRENT_TIMESTAMP
    ),
    (
        2002,
        'associated_funerary_object',
        'Ceramic vessel A',
        'Grog-tempered bowl',
        'Late Woodland',
        0,
        NULL,
        CURRENT_TIMESTAMP
    ),
    (
        2003,
        'associated_funerary_object',
        'Shell gorget',
        'Carved disc',
        'Unknown',
        0,
        NULL,
        CURRENT_TIMESTAMP
    ),
    (
        2004,
        'associated_funerary_object',
        'Red ochre packet',
        'Mineral pigment',
        'Precontact',
        0,
        NULL,
        CURRENT_TIMESTAMP
    ),
    (
        2005,
        'associated_funerary_object',
        'Bone awl',
        'Worked bone tool',
        NULL,
        0,
        NULL,
        CURRENT_TIMESTAMP
    ),
    (
        2006,
        'associated_funerary_object',
        'Copper bracelet',
        'Bent strip bracelet',
        NULL,
        0,
        NULL,
        CURRENT_TIMESTAMP
    ),
    (
        2007,
        'associated_funerary_object',
        'Vessel B',
        'Incised rim jar',
        'Unknown',
        0,
        NULL,
        CURRENT_TIMESTAMP
    ),
    (
        2008,
        'associated_funerary_object',
        'Stone pipe',
        'Catlinite pipe fragment',
        NULL,
        0,
        NULL,
        CURRENT_TIMESTAMP
    ),
    (
        2009,
        'associated_funerary_object',
        'Bead cache',
        'Mixed glass beads',
        '19th century',
        0,
        NULL,
        CURRENT_TIMESTAMP
    ),
    (
        2010,
        'associated_funerary_object',
        'Birch bark fragment',
        'Decorated bark panel',
        'Unknown',
        0,
        NULL,
        CURRENT_TIMESTAMP
    ),
    -- Unassociated funerary objects (8)
    (
        3001,
        'unassociated_funerary_object',
        'Copper pendant',
        'Cut copper sheet',
        NULL,
        0,
        NULL,
        CURRENT_TIMESTAMP
    ),
    (
        3002,
        'unassociated_funerary_object',
        'Ceramic vessel C',
        'Large storage jar',
        'Unknown',
        0,
        NULL,
        CURRENT_TIMESTAMP
    ),
    (
        3003,
        'unassociated_funerary_object',
        'Stone blade',
        'Chert blade',
        'Precontact',
        0,
        NULL,
        CURRENT_TIMESTAMP
    ),
    (
        3004,
        'unassociated_funerary_object',
        'Glass bead string',
        'Multicolor beads',
        '19th century',
        0,
        NULL,
        CURRENT_TIMESTAMP
    ),
    (
        3005,
        'unassociated_funerary_object',
        'Shell beads',
        'Columnella beads',
        NULL,
        0,
        NULL,
        CURRENT_TIMESTAMP
    ),
    (
        3006,
        'unassociated_funerary_object',
        'Copper tinklers',
        'Rolled copper cones',
        NULL,
        0,
        NULL,
        CURRENT_TIMESTAMP
    ),
    (
        3007,
        'unassociated_funerary_object',
        'Painted sherds',
        'Decorated ceramics',
        'Late Woodland',
        0,
        NULL,
        CURRENT_TIMESTAMP
    ),
    (
        3008,
        'unassociated_funerary_object',
        'Polished stone',
        'Greenstone celt fragment',
        'Unknown',
        0,
        NULL,
        CURRENT_TIMESTAMP
    ),
    -- Sacred objects (5)
    (
        4001,
        'sacred_object',
        'Ceremonial rattle',
        'Gourd rattle with seeds',
        'Historic',
        0,
        NULL,
        CURRENT_TIMESTAMP
    ),
    (
        4002,
        'sacred_object',
        'Prayer bundle',
        'Cloth-wrapped bundle',
        NULL,
        0,
        NULL,
        CURRENT_TIMESTAMP
    ),
    (
        4003,
        'sacred_object',
        'Drum',
        'Frame drum with rawhide',
        '20th century',
        0,
        NULL,
        CURRENT_TIMESTAMP
    ),
    (
        4004,
        'sacred_object',
        'Pipe stem',
        'Wooden stem',
        'Unknown',
        0,
        NULL,
        CURRENT_TIMESTAMP
    ),
    (
        4005,
        'sacred_object',
        'Feather fan',
        'Eagle feather fan',
        'Modern',
        0,
        NULL,
        CURRENT_TIMESTAMP
    ),
    -- Objects of cultural patrimony (5)
    (
        5001,
        'object_of_cultural_patrimony',
        'Ceremonial staff',
        'Carved wooden staff',
        '19th century',
        0,
        NULL,
        CURRENT_TIMESTAMP
    ),
    (
        5002,
        'object_of_cultural_patrimony',
        'Clan medallion',
        'Silver medallion',
        'ca. 1880',
        0,
        NULL,
        CURRENT_TIMESTAMP
    ),
    (
        5003,
        'object_of_cultural_patrimony',
        'Society regalia set',
        'Regalia components',
        'Historic',
        0,
        NULL,
        CURRENT_TIMESTAMP
    ),
    (
        5004,
        'object_of_cultural_patrimony',
        'Council wampum strand',
        'Shell wampum',
        'Precontact/Historic',
        0,
        NULL,
        CURRENT_TIMESTAMP
    ),
    (
        5005,
        'object_of_cultural_patrimony',
        'Ceremonial sash',
        'Beaded sash',
        '19th century',
        0,
        NULL,
        CURRENT_TIMESTAMP
    );

-- 7) Remains profiles
INSERT INTO
    remains_profile (
        item_id,
        remains_individual_min,
        remains_individual_max,
        remains_sex_estimation,
        remains_age_estimation,
        remains_osteology_notes
    )
VALUES
    (
        1001,
        1,
        1,
        'indeterminate',
        'Young Adult',
        'Healed cranial lesion.'
    ),
    (
        1002,
        1,
        1,
        'probable_male',
        'Adult',
        'Rib pathologies.'
    ),
    (
        1003,
        1,
        1,
        'indeterminate',
        'Adult',
        'Arsenic crystals noted.'
    ),
    (
        1004,
        1,
        1,
        'probable_female',
        'Adult',
        'Cranial vault only.'
    ),
    (
        1005,
        1,
        1,
        'indeterminate',
        'Older Adult',
        'Left femur absent.'
    ),
    (
        1006,
        1,
        1,
        'indeterminate',
        'Juvenile',
        'Deciduous teeth present.'
    ),
    (
        1007,
        1,
        1,
        'male',
        'Adult',
        'Teeth and mandible complete.'
    ),
    (
        1008,
        1,
        2,
        'indeterminate',
        'Adult',
        'Commingled fragments.'
    ),
    (
        1009,
        1,
        1,
        'indeterminate',
        'Adult',
        'Weathered cortical bone.'
    ),
    (
        1010,
        1,
        1,
        'indeterminate',
        'Infant',
        'Minimal ossification.'
    ),
    (
        1011,
        1,
        1,
        'indeterminate',
        'Adult',
        'Cranium intact; trauma absent.'
    ),
    (
        1012,
        1,
        1,
        'probable_male',
        'Adult',
        'Robust vertebrae.'
    );

-- 8) Item–Site links
INSERT INTO
    item_site (item_id, site_id, relation_role)
VALUES
    (1001, 501, 'findspot'),
    (1001, 504, 'reported_origin'),
    (1002, 501, 'findspot'),
    (1003, 506, 'probable_origin'),
    (1004, 502, 'findspot'),
    (1005, 501, 'findspot'),
    (1006, 507, 'findspot'),
    (1007, 505, 'probable_origin'),
    (1008, 508, 'reported_origin'),
    (1009, 509, 'findspot'),
    (1010, 510, 'probable_origin'),
    (1011, 503, 'findspot'),
    (1012, 502, 'reported_origin'),
    (2001, 501, 'findspot'),
    (2002, 503, 'findspot'),
    (2003, 503, 'reported_origin'),
    (2004, 505, 'findspot'),
    (2005, 505, 'probable_origin'),
    (2006, 504, 'reported_origin'),
    (2007, 502, 'findspot'),
    (2008, 502, 'findspot'),
    (2009, 505, 'reported_origin'),
    (2010, 502, 'probable_origin'),
    (3001, 504, 'reported_origin'),
    (3002, 504, 'reported_origin'),
    (3003, 502, 'findspot'),
    (3004, 505, 'reported_origin'),
    (3005, 502, 'probable_origin'),
    (3006, 503, 'findspot'),
    (3007, 505, 'findspot'),
    (3008, 503, 'reported_origin'),
    (4001, 503, 'reported_origin'),
    (4002, 506, 'probable_origin'),
    (4003, 506, 'reported_origin'),
    (4004, 503, 'findspot'),
    (4005, 502, 'reported_origin'),
    (5001, 503, 'reported_origin'),
    (5002, 505, 'probable_origin'),
    (5003, 505, 'reported_origin'),
    (5004, 506, 'reported_origin'),
    (5005, 510, 'reported_origin'),
    -- Hawaiian contexts
    (1008, 511, 'findspot'),
    (4002, 512, 'findspot'),
    (4005, 511, 'reported_origin');

-- 9) Holdings  (24 values per row, aligned)
INSERT INTO
    holding (
        holding_id,
        item_id,
        institution_id,
        holding_catalog_number,
        holding_accession_number,
        holding_collection_name,
        holding_acquisition,
        holding_source_party,
        holding_acquired_on,
        holding_type,
        holding_owns_title,
        holding_rop,
        holding_rop_basis,
        holding_storage_location,
        holding_on_exhibit,
        holding_condition_notes,
        holding_start_date,
        holding_end_date,
        holding_current,
        holding_summary_submit,
        holding_inv_complete,
        holding_accession_doc,
        holding_loan_agreement,
        holding_chain_of_custody
    )
VALUES
    -- 1001 moved GLUM → NSHM
    (
        7001,
        1001,
        10,
        'CAT-1958-036-A',
        'ACCN-1958-036',
        'Northern Field Collection',
        'field_collection',
        'University team',
        '1958-07-12',
        'possession',
        0,
        0,
        'Not established',
        'Room B12, Cab.3',
        0,
        'Stable',
        '1958-07-12',
        '1999-12-31',
        0,
        NULL,
        NULL,
        '/docs/ACCN-1958-036.pdf',
        NULL,
        NULL
    ),
    (
        7002,
        1001,
        11,
        'NSHM-2000-001',
        NULL,
        'Legacy Intake',
        'transfer',
        'GLUM',
        '2000-01-01',
        'control',
        0,
        0,
        'Inter-agency transfer',
        'Vault A',
        0,
        'Reboxed 2000',
        '2000-01-01',
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    -- Human remains 1002–1012 (current)
    (
        7003,
        1002,
        10,
        'CAT-1960-010',
        'ACCN-1960-010',
        'Northern Field Collection',
        'field_collection',
        NULL,
        '1960-06-01',
        'possession',
        0,
        0,
        NULL,
        'Room B12, Cab.4',
        0,
        NULL,
        '1960-06-01',
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        7004,
        1003,
        11,
        'NSHM-1975-001',
        NULL,
        'Legacy Intake',
        'transfer',
        'State Patrol',
        '1975-05-20',
        'control',
        0,
        0,
        'Custody only',
        'Vault 1',
        0,
        NULL,
        '1975-05-20',
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        7005,
        1004,
        12,
        'RVA-1981-220',
        NULL,
        'River Holdings',
        'donation',
        'Estate',
        '1981-10-10',
        'possession',
        1,
        0,
        'Deed of gift',
        'Cabinet C1',
        0,
        NULL,
        '1981-10-10',
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        7006,
        1005,
        13,
        'NPS-L-0001',
        NULL,
        'Recovered',
        'seizure',
        'NPS',
        '1990-01-08',
        'control',
        0,
        0,
        'Law enforcement',
        'Secure shelf',
        0,
        NULL,
        '1990-01-08',
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        7007,
        1006,
        15,
        'UPU-1999-001',
        NULL,
        'Teaching Coll.',
        'field_collection',
        NULL,
        '1999-04-04',
        'possession',
        0,
        0,
        NULL,
        'Room D1',
        0,
        NULL,
        '1999-04-04',
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        7008,
        1007,
        11,
        'NSHM-2001-010',
        NULL,
        'Archaeology',
        'purchase',
        'Private seller',
        '2001-07-07',
        'possession',
        1,
        0,
        'Bill of sale',
        'Exhibit 2',
        1,
        NULL,
        '2001-07-07',
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        7009,
        1008,
        17,
        'IRM-2005-015',
        NULL,
        'Hawaiian',
        'donation',
        'Community',
        '2005-05-05',
        'possession',
        1,
        0,
        NULL,
        'Sacred storage',
        0,
        NULL,
        '2005-05-05',
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        7010,
        1009,
        13,
        'NPS-L-0100',
        NULL,
        'Pigment',
        'transfer',
        'Army Corps',
        '2010-08-12',
        'control',
        0,
        0,
        NULL,
        'Vault 3',
        0,
        NULL,
        '2010-08-12',
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        7011,
        1010,
        14,
        'STATE-2012-045',
        NULL,
        'Bone Tools',
        'seizure',
        'State Police',
        '2012-02-02',
        'custody',
        0,
        0,
        NULL,
        'Evidence room',
        0,
        NULL,
        '2012-02-02',
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        7012,
        1011,
        10,
        'CAT-2015-001',
        NULL,
        'Osteology',
        'donation',
        'Community member',
        '2015-03-03',
        'possession',
        1,
        0,
        NULL,
        'Room D2',
        0,
        NULL,
        '2015-03-03',
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        7013,
        1012,
        11,
        'NSHM-2016-003',
        NULL,
        'Osteology',
        'field_collection',
        NULL,
        '2016-06-06',
        'possession',
        0,
        0,
        NULL,
        'Cabinet A1',
        0,
        NULL,
        '2016-06-06',
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    -- AFOs 2001–2010
    (
        7014,
        2001,
        10,
        'CAT-1999-001',
        NULL,
        'Ceramics',
        'field_collection',
        NULL,
        '1999-04-04',
        'possession',
        0,
        0,
        NULL,
        'Room D1',
        0,
        NULL,
        '1999-04-04',
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        7015,
        2002,
        11,
        'NSHM-2000-010',
        NULL,
        'Ceramics',
        'purchase',
        'Private seller',
        '2000-07-07',
        'possession',
        1,
        0,
        'Invoice on file',
        'Exhibit 2',
        1,
        NULL,
        '2000-07-07',
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        7016,
        2003,
        12,
        'RVA-2005-015',
        NULL,
        'Shell',
        'donation',
        'Collector',
        '2005-05-05',
        'possession',
        1,
        0,
        NULL,
        'Cabinet B2',
        0,
        NULL,
        '2005-05-05',
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        7017,
        2004,
        13,
        'NPS-L-0101',
        NULL,
        'Pigment',
        'transfer',
        'Army Corps',
        '2010-08-12',
        'control',
        0,
        0,
        NULL,
        'Vault 3',
        0,
        NULL,
        '2010-08-12',
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        7018,
        2005,
        14,
        'STATE-2012-046',
        NULL,
        'Bone Tools',
        'seizure',
        'State Police',
        '2012-02-02',
        'custody',
        0,
        0,
        NULL,
        'Evidence room',
        0,
        NULL,
        '2012-02-02',
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        7019,
        2006,
        10,
        'CAT-2015-002',
        NULL,
        'Copper',
        'donation',
        'Community member',
        '2015-03-03',
        'possession',
        1,
        0,
        NULL,
        'Room D2',
        0,
        NULL,
        '2015-03-03',
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        7020,
        2007,
        11,
        'NSHM-2016-002',
        NULL,
        'Ceramics',
        'field_collection',
        NULL,
        '2016-06-06',
        'possession',
        0,
        0,
        NULL,
        'Cabinet A1',
        0,
        NULL,
        '2016-06-06',
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        7021,
        2008,
        12,
        'RVA-2017-003',
        NULL,
        'Pipes',
        'purchase',
        'Dealer',
        '2017-07-07',
        'possession',
        1,
        0,
        NULL,
        'Drawer P1',
        0,
        NULL,
        '2017-07-07',
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        7022,
        2009,
        13,
        'NPS-L-0200',
        NULL,
        'Beads',
        'transfer',
        'State Museum',
        '2018-08-08',
        'control',
        0,
        0,
        NULL,
        'Vault 2',
        0,
        NULL,
        '2018-08-08',
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        7023,
        2010,
        14,
        'STATE-2019-010',
        NULL,
        'Bark',
        'donation',
        'Private donor',
        '2019-09-09',
        'possession',
        1,
        0,
        NULL,
        'Cabinet X',
        0,
        NULL,
        '2019-09-09',
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    -- UAO 3001–3008
    (
        7024,
        3001,
        10,
        'CAT-2020-001',
        NULL,
        'UAO',
        'donation',
        'Family',
        '2020-01-01',
        'possession',
        1,
        0,
        NULL,
        'Textile drawer',
        0,
        NULL,
        '2020-01-01',
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        7025,
        3002,
        11,
        'NSHM-2020-050',
        NULL,
        'UAO',
        'seizure',
        'State',
        '2020-05-05',
        'custody',
        0,
        0,
        NULL,
        'Secure box',
        0,
        NULL,
        '2020-05-05',
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        7026,
        3003,
        12,
        'RVA-2021-012',
        NULL,
        'UAO',
        'donation',
        'Community',
        '2021-02-02',
        'possession',
        1,
        0,
        NULL,
        'Case 3',
        0,
        NULL,
        '2021-02-02',
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        7027,
        3004,
        13,
        'NPS-L-0300',
        NULL,
        'UAO',
        'field_collection',
        NULL,
        '2021-03-03',
        'control',
        0,
        0,
        NULL,
        'Vault 4',
        0,
        NULL,
        '2021-03-03',
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        7028,
        3005,
        14,
        'STATE-2021-099',
        NULL,
        'UAO',
        'seizure',
        'Wildlife',
        '2021-04-04',
        'custody',
        0,
        0,
        NULL,
        'Evidence cold',
        0,
        NULL,
        '2021-04-04',
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        7029,
        3006,
        10,
        'CAT-2022-010',
        NULL,
        'UAO',
        'donation',
        'Community',
        '2022-01-15',
        'possession',
        1,
        0,
        NULL,
        'Drawer 7',
        0,
        NULL,
        '2022-01-15',
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        7030,
        3007,
        11,
        'NSHM-2022-020',
        NULL,
        'UAO',
        'purchase',
        'Dealer',
        '2022-02-20',
        'possession',
        1,
        0,
        NULL,
        'Exhibit 5',
        1,
        NULL,
        '2022-02-20',
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        7031,
        3008,
        12,
        'RVA-2022-030',
        NULL,
        'UAO',
        'donation',
        'Community',
        '2022-03-25',
        'possession',
        1,
        0,
        NULL,
        'Shelf B',
        0,
        NULL,
        '2022-03-25',
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    -- Sacred 4001–4005
    (
        7032,
        4001,
        10,
        'CAT-2022-040',
        NULL,
        'Sacred',
        'donation',
        'Community',
        '2022-04-01',
        'possession',
        1,
        0,
        NULL,
        'Sacred storage',
        0,
        NULL,
        '2022-04-01',
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        7033,
        4002,
        10,
        'CAT-2023-011',
        NULL,
        'Sacred',
        'donation',
        'Community',
        '2023-05-10',
        'possession',
        1,
        0,
        NULL,
        'Sacred storage',
        0,
        NULL,
        '2023-05-10',
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        7034,
        4003,
        12,
        'RVA-2021-040',
        NULL,
        'Instruments',
        'donation',
        'Community',
        '2021-02-02',
        'possession',
        1,
        0,
        NULL,
        'Music case',
        0,
        NULL,
        '2021-02-02',
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        7035,
        4004,
        13,
        'NPS-L-0410',
        NULL,
        'Pipes',
        'field_collection',
        NULL,
        '2022-09-09',
        'control',
        0,
        0,
        NULL,
        'Vault 6',
        0,
        NULL,
        '2022-09-09',
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        7036,
        4005,
        17,
        'IRM-2021-099',
        NULL,
        'Feathers',
        'seizure',
        'Wildlife',
        '2021-04-04',
        'custody',
        0,
        0,
        NULL,
        'Evidence cold',
        0,
        NULL,
        '2021-04-04',
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    -- Patrimony 5001–5005
    (
        7037,
        5001,
        10,
        'CAT-2022-050',
        NULL,
        'Staffs',
        'donation',
        'Community',
        '2022-01-15',
        'possession',
        1,
        0,
        NULL,
        'Sacred storage',
        0,
        NULL,
        '2022-01-15',
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        7038,
        5002,
        11,
        'NSHM-2022-060',
        NULL,
        'Medallions',
        'purchase',
        'Dealer',
        '2022-02-20',
        'possession',
        1,
        0,
        NULL,
        'Exhibit 5',
        1,
        NULL,
        '2022-02-20',
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        7039,
        5003,
        12,
        'RVA-2022-070',
        NULL,
        'Regalia',
        'donation',
        'Community',
        '2022-03-25',
        'possession',
        1,
        0,
        NULL,
        'Textiles shelf',
        0,
        NULL,
        '2022-03-25',
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        7040,
        5004,
        13,
        'NPS-L-0400',
        NULL,
        'Wampum',
        'transfer',
        'Another agency',
        '2022-04-18',
        'control',
        0,
        0,
        NULL,
        'Vault 6',
        0,
        NULL,
        '2022-04-18',
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        7041,
        5005,
        14,
        'STATE-2022-080',
        NULL,
        'Sashes',
        'donation',
        'Family',
        '2022-05-30',
        'possession',
        1,
        0,
        NULL,
        'Textile drawer',
        0,
        NULL,
        '2022-05-30',
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    );

-- 10) Affiliations
INSERT INTO
    affiliation (
        affiliation_id,
        item_id,
        community_id,
        affiliation_type,
        affiliation_basis,
        affiliation_determined
    )
VALUES
    (
        8001,
        1001,
        1,
        'cultural',
        'Archaeological context + oral histories',
        '2023-08-20'
    ),
    (
        8002,
        1002,
        5,
        'cultural',
        'Mortuary pattern; site proximity',
        '2023-06-10'
    ),
    (
        8003,
        1003,
        1,
        'cultural',
        'Historical records; chemical treatment note',
        '2024-01-05'
    ),
    (
        8004,
        1004,
        2,
        'lineal',
        'Documented descendant statement',
        '2024-05-05'
    ),
    (
        8005,
        2001,
        1,
        'cultural',
        'Found with 1001 at Site 501',
        '2023-08-20'
    ),
    (
        8006,
        3006,
        5,
        'cultural',
        'Copper tradition in region',
        '2020-03-03'
    ),
    (
        8007,
        4001,
        1,
        'cultural',
        'Community testimony (sacred)',
        '2022-11-01'
    ),
    (
        8008,
        5001,
        5,
        'cultural',
        'Regalia lineage',
        '2022-12-12'
    ),
    (
        8009,
        4003,
        6,
        'cultural',
        'NHO stewardship',
        '2021-03-01'
    ),
    (
        8010,
        1008,
        10,
        'cultural',
        'Kūpuna iwi; community identification',
        '2021-07-20'
    ),
    (
        8011,
        5004,
        9,
        'cultural',
        'Historical council records',
        '2023-04-12'
    ),
    (
        8012,
        3004,
        3,
        'cultural',
        'Regional cemetery assemblage',
        '2022-05-10'
    ),
    (
        8013,
        1011,
        9,
        'cultural',
        'Oral history alignment',
        '2024-01-30'
    );

-- 11) Consultations
INSERT INTO
    consultation (
        consult_id,
        item_id,
        community_id,
        institution_id,
        consult_started_on,
        consult_last_meeting,
        consult_status,
        consult_notes
    )
VALUES
    (
        9001,
        1001,
        1,
        11,
        '2023-01-15',
        '2024-02-15',
        'in_progress',
        'Awaiting hazard confirmation'
    ),
    (
        9002,
        2001,
        1,
        10,
        '2023-01-15',
        '2024-03-10',
        'in_progress',
        'Associated with 1001'
    ),
    (
        9003,
        4001,
        1,
        10,
        '2022-10-01',
        '2023-05-12',
        'complete',
        'Approved for repatriation'
    ),
    (
        9004,
        4003,
        6,
        12,
        '2021-04-01',
        '2021-06-01',
        'complete',
        'Transfer planned'
    ),
    (
        9005,
        5001,
        5,
        10,
        '2022-12-01',
        '2023-03-01',
        'paused',
        'Awaiting additional documentation'
    ),
    (
        9006,
        1003,
        1,
        11,
        '2024-01-10',
        '2024-05-05',
        'in_progress',
        'Arsenic mitigation discussion'
    ),
    (
        9007,
        1008,
        10,
        17,
        '2021-05-01',
        '2021-07-20',
        'complete',
        'Cultural care plan agreed'
    ),
    (
        9008,
        5004,
        9,
        13,
        '2023-02-01',
        '2023-04-15',
        'in_progress',
        'Wampum council consultation'
    ),
    (
        9009,
        3006,
        5,
        10,
        '2020-01-20',
        '2020-03-03',
        'complete',
        'Returned as associated set'
    ),
    (
        9010,
        1011,
        9,
        10,
        '2024-01-15',
        '2024-02-10',
        'in_progress',
        'Discussing osteology summary'
    );

-- 12) Repatriation requests
INSERT INTO
    repatriation_request (
        request_id,
        item_id,
        requesting_community_id,
        request_received_on,
        request_acknowledged_on,
        request_decision,
        request_decision_on,
        request_basis
    )
VALUES
    (
        9101,
        4001,
        1,
        '2023-06-01',
        '2023-06-05',
        'approved',
        '2023-07-01',
        'Sacred object; affiliation established'
    ),
    (
        9102,
        1001,
        1,
        '2024-03-10',
        '2024-03-25',
        'pending',
        NULL,
        'Affiliation established; hazard review'
    ),
    (
        9103,
        4003,
        6,
        '2021-05-01',
        '2021-05-05',
        'approved',
        '2021-06-01',
        'NHO request and documentation'
    ),
    (
        9104,
        5001,
        5,
        '2023-02-10',
        '2023-02-12',
        'pending',
        NULL,
        'Cultural patrimony claim'
    ),
    (
        9105,
        1004,
        2,
        '2024-05-05',
        '2024-05-08',
        'approved',
        '2024-06-15',
        'Lineal descendant statement'
    ),
    (
        9106,
        3006,
        5,
        '2020-02-10',
        '2020-02-12',
        'approved',
        '2020-03-03',
        'Resolved as associated set'
    ),
    (
        9107,
        5004,
        9,
        '2023-04-20',
        '2023-04-25',
        'denied',
        '2023-06-30',
        'Insufficient documentation (in progress)'
    ),
    (
        9108,
        1008,
        10,
        '2021-06-01',
        '2021-06-03',
        'withdrawn',
        '2021-07-15',
        'Replaced by community care agreement'
    ),
    (
        9109,
        1011,
        9,
        '2024-02-01',
        '2024-02-05',
        'pending',
        NULL,
        'Community request under review'
    );

-- 13) Transfers
INSERT INTO
    transfer (
        transfer_id,
        item_id,
        from_institution_id,
        to_community_id,
        transfer_scheduled_on,
        transfer_completed_on,
        transfer_transport,
        transfer_location,
        transfer_tracking_number,
        transfer_handover_contact,
        transfer_receive_contact,
        transfer_chain_of_custody_document,
        transfer_notes
    )
VALUES
    (
        9201,
        4001,
        10,
        1,
        '2023-07-10',
        '2023-07-18',
        'Hand-carry by trained courier',
        'Collections Room B12 (GLUM)',
        'UPS 1Z999AA10123456784',
        100,
        101,
        '/docs/COC-2023-07-18.pdf',
        'Ceremonial protocols observed'
    ),
    (
        9202,
        4003,
        12,
        6,
        '2021-06-10',
        '2021-06-15',
        'Courier',
        'RVA Loading Dock',
        NULL,
        102,
        103,
        '/docs/COC-2021-06-15.pdf',
        ''
    ),
    (
        9203,
        1004,
        12,
        2,
        '2024-07-10',
        '2024-07-18',
        'Hand-carry',
        'THPO office',
        NULL,
        102,
        101,
        NULL,
        'Lineal descendant present'
    ),
    (
        9204,
        3006,
        10,
        5,
        '2020-03-05',
        '2020-03-10',
        'Courier',
        'GLUM Dock',
        'GLUM12345',
        100,
        106,
        '/docs/COC-2020-03-10.pdf',
        'Reassociated set'
    ),
    (
        9205,
        1008,
        17,
        10,
        '2021-07-10',
        NULL,
        'Ceremonial escort',
        'Honolulu facility',
        NULL,
        109,
        113,
        NULL,
        'Awaiting final ceremony'
    ),
    (
        9206,
        5004,
        13,
        9,
        '2023-07-20',
        NULL,
        'Courier',
        'NPS Regional',
        'NPS-TRACK-445',
        112,
        111,
        NULL,
        'Decision under appeal'
    ),
    (
        9207,
        4005,
        17,
        10,
        '2021-08-01',
        '2021-08-05',
        'Courier',
        'Honolulu airport',
        'HAW-555-2021',
        118,
        113,
        '/docs/COC-2021-08-05.pdf',
        'Feathers returned per permits'
    ),
    (
        9208,
        4002,
        10,
        1,
        '2024-09-01',
        NULL,
        'Hand-carry',
        'GLUM secure room',
        NULL,
        100,
        101,
        NULL,
        'Scheduled after FR notice'
    );

-- Advance identity sequences beyond the explicit seed IDs.
select setval(pg_get_serial_sequence('community','community_id'), coalesce((select max(community_id) from community),1), true);
select setval(pg_get_serial_sequence('institution','institution_id'), coalesce((select max(institution_id) from institution),1), true);
select setval(pg_get_serial_sequence('contact','contact_id'), coalesce((select max(contact_id) from contact),1), true);
select setval(pg_get_serial_sequence('discovery_site','site_id'), coalesce((select max(site_id) from discovery_site),1), true);
select setval(pg_get_serial_sequence('cultural_item','item_id'), coalesce((select max(item_id) from cultural_item),1), true);
select setval(pg_get_serial_sequence('holding','holding_id'), coalesce((select max(holding_id) from holding),1), true);
select setval(pg_get_serial_sequence('affiliation','affiliation_id'), coalesce((select max(affiliation_id) from affiliation),1), true);
select setval(pg_get_serial_sequence('consultation','consult_id'), coalesce((select max(consult_id) from consultation),1), true);
select setval(pg_get_serial_sequence('repatriation_request','request_id'), coalesce((select max(request_id) from repatriation_request),1), true);
select setval(pg_get_serial_sequence('transfer','transfer_id'), coalesce((select max(transfer_id) from transfer),1), true);


commit;
