-- NAGPRA Repatriation Workflow Database
-- Supabase/PostgreSQL port of the original MySQL coursework schema.
-- Migration 1/5: creates the relational schema and public-safe projection table.

begin;

create table if not exists community (
  community_id integer generated by default as identity primary key,
  community_type text not null check (community_type in ('tribe','NHO')),
  community_name varchar(255) not null unique,
  community_federal_status text not null check (community_federal_status in ('federally_recognized','state_recognized','unrecognized','n/a - NHO')),
  community_thpo_office varchar(255),
  community_thpo_recognized smallint not null default 0 check (community_thpo_recognized in (0,1)),
  community_thpo_recognized_on date,
  community_website varchar(255),
  community_notes text
);

create table if not exists institution (
  institution_id integer generated by default as identity primary key,
  institution_name varchar(255) not null unique,
  institution_type text not null check (institution_type in ('museum','university','federal_agency','state_agency','private_collection','other')),
  institution_address_street varchar(255),
  institution_city varchar(64) not null,
  institution_state varchar(64) not null,
  institution_postal_code varchar(10) not null,
  institution_country varchar(32) not null,
  institution_nps_org_id varchar(64),
  institution_notes text
);

create table if not exists contact (
  contact_id integer generated by default as identity primary key,
  contact_name varchar(255) not null,
  contact_role text not null check (contact_role in ('THPO','EldersCouncil','Curator','CollectionsMgr','Legal','Researcher','Other')),
  contact_email varchar(255),
  contact_phone varchar(50),
  contact_community_id integer references community(community_id) on delete set null on update cascade,
  contact_institution_id integer references institution(institution_id) on delete set null on update cascade
);

create index if not exists idx_contact_community on contact(contact_community_id);
create index if not exists idx_contact_institution on contact(contact_institution_id);

create table if not exists cultural_item (
  item_id integer generated by default as identity primary key,
  item_category text not null check (item_category in ('human_remains','associated_funerary_object','unassociated_funerary_object','sacred_object','object_of_cultural_patrimony')),
  item_title varchar(255),
  item_description text,
  item_date_range varchar(255),
  item_haz_treated smallint not null default 0 check (item_haz_treated in (0,1)),
  item_haz_notes text,
  item_created_at timestamptz not null default now()
);

create table if not exists remains_profile (
  item_id integer primary key references cultural_item(item_id) on delete cascade on update cascade,
  remains_individual_min integer,
  remains_individual_max integer,
  remains_sex_estimation text check (remains_sex_estimation in ('indeterminate','probable_male','male','probable_female','female')),
  remains_age_estimation varchar(64),
  remains_osteology_notes text,
  check (remains_individual_min is null or remains_individual_min >= 0),
  check (remains_individual_max is null or remains_individual_max >= 0),
  check (remains_individual_min is null or remains_individual_max is null or remains_individual_max >= remains_individual_min)
);

create table if not exists discovery_site (
  site_id integer generated by default as identity primary key,
  site_name varchar(255),
  site_county varchar(64),
  site_state varchar(64) not null,
  site_country varchar(32) not null,
  site_latitude numeric(9,6),
  site_longitude numeric(9,6),
  site_restricted smallint default 1 check (site_restricted in (0,1)),
  site_sensitive_notes text,
  check (site_latitude is null or site_latitude between -90 and 90),
  check (site_longitude is null or site_longitude between -180 and 180)
);

create table if not exists item_site (
  item_id integer not null references cultural_item(item_id) on delete cascade on update cascade,
  site_id integer not null references discovery_site(site_id) on delete cascade on update cascade,
  relation_role text not null default 'findspot' check (relation_role in ('findspot','probable_origin','reported_origin','other')),
  primary key (item_id, site_id)
);
create index if not exists idx_item_site_site on item_site(site_id);

create table if not exists holding (
  holding_id integer generated by default as identity primary key,
  item_id integer not null references cultural_item(item_id) on delete restrict on update cascade,
  institution_id integer not null references institution(institution_id) on delete restrict on update cascade,
  holding_catalog_number varchar(120),
  holding_accession_number varchar(120),
  holding_collection_name varchar(255),
  holding_acquisition text default 'unknown' check (holding_acquisition in ('donation','purchase','field_collection','transfer','seizure','unknown')),
  holding_source_party varchar(255),
  holding_acquired_on date,
  holding_type text not null default 'possession' check (holding_type in ('possession','control','custody')),
  holding_owns_title smallint not null default 0 check (holding_owns_title in (0,1)),
  holding_rop smallint not null default 0 check (holding_rop in (0,1)),
  holding_rop_basis text,
  holding_storage_location varchar(255),
  holding_on_exhibit smallint not null default 0 check (holding_on_exhibit in (0,1)),
  holding_condition_notes text,
  holding_start_date date not null,
  holding_end_date date,
  holding_current smallint not null default 1 check (holding_current in (0,1)),
  holding_summary_submit date,
  holding_inv_complete date,
  holding_accession_doc varchar(255),
  holding_loan_agreement varchar(255),
  holding_chain_of_custody varchar(255)
);
create index if not exists idx_holding_item on holding(item_id);
create index if not exists idx_holding_institution on holding(institution_id);
create unique index if not exists uq_holding_one_current_per_item on holding(item_id) where holding_current = 1;

create table if not exists affiliation (
  affiliation_id integer generated by default as identity primary key,
  item_id integer not null references cultural_item(item_id) on delete cascade on update cascade,
  community_id integer not null references community(community_id) on delete restrict on update cascade,
  affiliation_type text not null check (affiliation_type in ('lineal','cultural')),
  affiliation_basis text,
  affiliation_determined date,
  unique (item_id, community_id, affiliation_type)
);
create index if not exists idx_affiliation_item on affiliation(item_id);
create index if not exists idx_affiliation_community on affiliation(community_id);

create table if not exists consultation (
  consult_id integer generated by default as identity primary key,
  item_id integer not null references cultural_item(item_id) on delete cascade on update cascade,
  community_id integer not null references community(community_id) on delete restrict on update cascade,
  institution_id integer not null references institution(institution_id) on delete restrict on update cascade,
  consult_started_on date,
  consult_last_meeting date,
  consult_status text not null default 'in_progress' check (consult_status in ('not_started','in_progress','paused','complete')),
  consult_notes text
);
create index if not exists idx_consultation_item on consultation(item_id);
create index if not exists idx_consultation_community on consultation(community_id);
create index if not exists idx_consultation_institution on consultation(institution_id);

create table if not exists repatriation_request (
  request_id integer generated by default as identity primary key,
  item_id integer not null references cultural_item(item_id) on delete cascade on update cascade,
  requesting_community_id integer not null references community(community_id) on delete restrict on update cascade,
  request_received_on date not null,
  request_acknowledged_on date,
  request_decision text not null default 'pending' check (request_decision in ('approved','pending','denied','withdrawn')),
  request_decision_on date,
  request_basis text
);
create index if not exists idx_request_item on repatriation_request(item_id);
create index if not exists idx_request_community on repatriation_request(requesting_community_id);

create table if not exists transfer (
  transfer_id integer generated by default as identity primary key,
  item_id integer not null references cultural_item(item_id) on delete cascade on update cascade,
  from_institution_id integer not null references institution(institution_id) on delete restrict on update cascade,
  to_community_id integer not null references community(community_id) on delete restrict on update cascade,
  transfer_scheduled_on date,
  transfer_completed_on date,
  transfer_transport varchar(120),
  transfer_location varchar(120),
  transfer_tracking_number varchar(64),
  transfer_handover_contact integer references contact(contact_id) on delete set null on update cascade,
  transfer_receive_contact integer references contact(contact_id) on delete set null on update cascade,
  transfer_chain_of_custody_document varchar(255),
  transfer_notes text
);
create index if not exists idx_transfer_item on transfer(item_id);
create index if not exists idx_transfer_from_institution on transfer(from_institution_id);
create index if not exists idx_transfer_to_community on transfer(to_community_id);

-- A separate, sanitized table is the ONLY table exposed to the public portfolio UI.
-- It intentionally omits contact information, hazard notes, exact site data, storage locations,
-- tracking numbers, chain-of-custody paths, and other sensitive operational fields.
create table if not exists portfolio_item (
  item_id integer primary key,
  item_title varchar(255),
  category text not null,
  institution_name varchar(255) not null,
  communities text not null default 'Unaffiliated',
  holding_since date
);

commit;
